#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 28 12:51:51 MDT 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim pit_tb_behav -key {Behavioral:sim_1:Functional:pit_tb} -tclbatch pit_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /auto/fsb/ryan9801/ecen427/hw/ip_repo/pit/pit_tb_behav.wcfg -log simulate.log"
xsim pit_tb_behav -key {Behavioral:sim_1:Functional:pit_tb} -tclbatch pit_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /auto/fsb/ryan9801/ecen427/hw/ip_repo/pit/pit_tb_behav.wcfg -log simulate.log

